### ISSUE TITLE
Snipeit- Exception couldn't save customfieldset

### ISSUE THREAD

**Issue by manisha-tanwar** [t3n/helm-charts#137]
Getting Exception : couldn't save customfieldset
when using external database, it works fine when I use internal mysql.

This is what I've in database:

mysql> select * from custom_fields;
+----+-------------+-----------------------------------------------------------------------------------------------------+---------+------------+------------+
| id | name | format | element | created_at | updated_at |
+----+-------------+-----------------------------------------------------------------------------------------------------+---------+------------+------------+
| 1 | MAC Address | regex:/^[a-fA-F0-9]{2}:[a-fA-F0-9]{2}:[a-fA-F0-9]{2}:[a-fA-F0-9]{2}:[a-fA-F0-9]{2}:[a-fA-F0-9]{2}$/ | text | NULL | NULL |
+----+-------------+-----------------------------------------------------------------------------------------------------+---------+------------+------------+
1 row in set (0.00 sec)

mysql> select * from custom_field_custom_fieldset;
Empty set (0.00 sec)

mysql> select * from custom_fieldsets;
+----+------------------------+
| id | name |
+----+------------------------+
| 1 | Asset with MAC Address |
+----+------------------------+
1 row in set (0.00 sec)

mysql> select * from custom_field_custom_fieldset;
Empty set (0.00 sec)

mysql> desc custom_field_custom_fieldset;
+--------------------+------------+------+-----+---------+-------+
| Field | Type | Null | Key | Default | Extra |
+--------------------+------------+------+-----+---------+-------+
| custom_field_id | int(11) | NO | | NULL | |
| custom_fieldset_id | int(11) | NO | | NULL | |
| order | int(11) | NO | | NULL | |
| required | tinyint(1) | NO | | NULL | |
+--------------------+------------+------+-----+---------+-------+
4 rows in set (0.00 sec)

```
[2021-02-10 16:35:25] production.ERROR: couldn't save customfieldset {"exception":"[object] (Exception(code: 0): couldn't save customfieldset at /var/www/html/database/migrations/2015_09_22_003413_migrate_mac_address.php:20)#75 /var/www/html/app/Http/Middleware/ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#76 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))


```

Please help!

**Comment by manisha-tanwar** [comment]
Got it resolved following https://snipe-it.readme.io/docs/docker
and help from https://gitter.im/snipe/snipe-it#

> WARNING:
> 
> Newer MySQL containers (5.7 and later, or MariaDB) may run in strict-mode by default, and the initial migrations and application setup will fail in strict mode. If you want to use one of those versions, you need to disable strict mode first!


This is what I did
```
SET GLOBAL pxc_strict_mode=PERMISSIVE
Then run your snipeit stuff then reset it back
SET GLOBAL pxc_strict_mode=ENFORCING

```
